### ISSUE TITLE
Several errors after update to 2.0.0

### ISSUE THREAD

**Issue by fklement** [Wikiki/bulma-carousel#35]
Maybe the problem is me but:  
* Couldn't find `bulma-carousel.sass`
```
Module build failed: ModuleBuildError: Module build failed:
@import "~bulma-carousel";
^
      File to import not found or unreadable: ~bulma-carousel.
```

* Autoplay doesn't work 
* Navigation between slider images doesn't work either

**Comment by Wikiki** [comment]
Sorry. This is now working as expected

**Comment by fklement** [comment]
No problem at all.
I installed version 2.0.6 and rebuild everything. 
But autoplay and navigation is still not working.

**Comment by Wikiki** [comment]
This is weird it's working on the demo site :-(

**Comment by fklement** [comment]
Damn that was my mistake.  
But now i've found some other strange behaviours:
* It's not possible anymore to drag the picture to the left or right
* Weird looking white image showing up when navigating backwards

**Comment by Wikiki** [comment]
Swipe functionality has been fixed.

I'll have a look on the other issue (if I get it on my side)

**Comment by Wikiki** [comment]
Hi again,

can you please try again. I think it should be fixed.

**Comment by fklement** [comment]
Thank you very much for your efford.
But the errors still persist in my application.

**Comment by Wikiki** [comment]
both of them ?
The swipe only work with touche gesture (no mouse)

**Comment by fklement** [comment]
Ah ok didn't know that.
But now i'm getting this error message:
```
main.js:9177 Uncaught ReferenceError: touchObj is not defined
    at c._swipeStart (main.js:9177)
    at HTMLDivElement.<anonymous> (main.js:9147)
_swipeStart @ main.js:9177
(anonymous) @ main.js:9147

main.js:9182 Uncaught TypeError: Cannot read property 'start' of undefined
    at c._swipeEnd (main.js:9182)
    at HTMLDivElement.<anonymous> (main.js:9151)
_swipeEnd @ main.js:9182
(anonymous) @ main.js:9151
```

**Comment by Wikiki** [comment]
Arf my last commit got into develop branch and not master....I'll update it this evening. Sorry

**Comment by Wikiki** [comment]
I just update the master branch and the npm package.
Thanks for all your tests and feedback

**Comment by Wikiki** [comment]
Hi, he last update v2.0.14 should have fixed your issues (and add swipe by mouse available too)

**Comment by fklement** [comment]
No in the docs everything is fine.
Thx!

**Comment by Wikiki** [comment]
Weird. Maybe it's anbug with vue. Have you the possibility to share your code ?

**Comment by Wikiki** [comment]
Ho wait: how many images do you have in your carousel ? It could be a bug with less than 3 images....

**Comment by fklement** [comment]
Sure here is the html part:
```php
	if(count($page->images)) {
		$wrapper =  "<h1 class='title is-1'>" . $page->get('headline|title') . "</h1>
						<div class='carousel carousel-animated carousel-animate-slide mb4' data-autoplay='true' style='height: 500px;'>
							<div class='carousel-container' style='height: 500px;'>";
		foreach($page->images as $image){
			$wrapper .= "<div class='carousel-item has-background'>
							<img class='is-background' src='$image->url' alt='$image->description' width='640' height='310' />
						</div>";
		}

		$wrapper .="	</div>
						<div class='carousel-navigation is-overlay'>
							<div class='carousel-nav-left'>
								<i class='fa fa-chevron-left' aria-hidden='true'></i>
							</div>
							<div class='carousel-nav-right'>
								<i class='fa fa-chevron-right' aria-hidden='true'></i>
							</div>
						</div>
					</div>";

		echo $wrapper;
	}					
<!-- end slider -->
```

You're right. When i upload more then 2 images, the problem does not appear.

**Comment by Wikiki** [comment]
I'll have a look at this. I don't know how to handle this case without duplicating the first item now.
